### ISSUE TITLE
npm install leads to error

### ISSUE THREAD

**Issue by carstengericke** [sailpoint-oss/discourse-connector-2#5]
I cloned the repository and tried to run: npm install
This leads to the following error:
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/sailpoint/saas-connector-sdk-js.git
npm ERR! ERROR: Repository not found.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

Has the repository path changed?

**Comment by colin-mckibben-sp** [comment]
Thanks for finding this.  I updated the path to the connector sdk.  Can you pull the latest changes and try again?

**Comment by carstengericke** [comment]
This has fixed the issue.
